"""Add reviews and ratings tables 3

Revision ID: 46a36ba63f5d
Revises: 455ce28d6211
Create Date: 2025-01-31 00:43:11.932501

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '46a36ba63f5d'
down_revision: Union[str, None] = '455ce28d6211'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
